MXECOMRC - COMMON RECOVERY ESTAE/ARR/FRR
MXEEOTXR - END OF TASK EXIT ROUTINE
MXEINLPA - LPA FUNCTION PACK
MXEMSGTB - MESSAGE TABLE
MXESRBRQ - SRB REQUEST HANDLER FOR QUERY
MXESRVLD - SERVER SUBTASK FOR LOGDATA QUEUE
MXESRVMN - SERVER MAIN TASK
MXESRVPC - PC-SS ROUTINE
MXESRVRM - SERVER ASID LEVEL RESMGR ROUTINE
MXETMRXR - STIMERM EXIT
MXETSO   - CLIENT TSO PROGRAM
