MXEMSGTB TITLE 'MXE MESSAGE TABLE'
MXEMSGTB CSECT
MXEMSGTB AMODE 31
MXEMSGTB RMODE ANY
*
* INDEX DEFINITION MUST COME FIRST BEFORE ANY MESSAGE TABLE
* TEMPLATE STATEMENTS
*
         MXEMSGDF INDEX,MAX=10
*
*
* MESSAGE TABLE ENTRIES
*
         MXEMSGDF START,NUM=0001,SEV=E
         MXEMSGDF TEXT,' PARSE ERROR - RESPECIFY COMMAND'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0002,SEV=I
         MXEMSGDF TEXT,' SERVICE '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' RC='
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' RSN='
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0003,SEV=I
         MXEMSGDF TEXT,' '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' *'
         MXEMSGDF OVERLAY,'................'
         MXEMSGDF TEXT,'* '
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0004,SEV=I
         MXEMSGDF TEXT,' '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' TASK STARTED'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0005,SEV=I
         MXEMSGDF TEXT,' '
         MXEMSGDF OVERLAY,'........'
         MXEMSGDF TEXT,' TASK STOPPED'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0006,SEV=I
         MXEMSGDF TEXT,' SERVICES ESTABLISHED'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0007,SEV=I
         MXEMSGDF TEXT,' EMERGENCY SHUTDOWN'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0008,SEV=I
         MXEMSGDF TEXT,' SERVICES REMOVED'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0009,SEV=I
         MXEMSGDF TEXT,' COMMAND ACCEPTED'
         MXEMSGDF END
*
         MXEMSGDF START,NUM=0010,SEV=E
         MXEMSGDF TEXT,' INVALID COMMAND'
         MXEMSGDF END
*
         END
